/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef openstarsprofile_CONSTANTS_H
#define openstarsprofile_CONSTANTS_H

#include "openstarsprofile_types.h"

namespace OpenStars { namespace Platform { namespace Profile {

class openstarsprofileConstants {
 public:
  openstarsprofileConstants();

};

extern const openstarsprofileConstants g_openstarsprofile_constants;

}}} // namespace

#endif
