/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "openstarsprofile_constants.h"

namespace OpenStars { namespace Platform { namespace Profile {

const openstarsprofileConstants g_openstarsprofile_constants;

openstarsprofileConstants::openstarsprofileConstants() {
}

}}} // namespace

