/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef openstarsprofile_TYPES_H
#define openstarsprofile_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace OpenStars { namespace Platform { namespace Profile {

struct TErrorCode {
  enum type {
    EGood = 0,
    ENotFound = -1,
    EUnknown = -2,
    EDataExisted = -3
  };
};

extern const std::map<int, const char*> _TErrorCode_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const TErrorCode::type& val);

typedef int64_t TKey;

typedef class TPlatformProfile TData;

class TPlatformProfile;

class TDataResult;

typedef struct _TPlatformProfile__isset {
  _TPlatformProfile__isset() : uid(false), username(false), displayName(false), trustedEmails(false), trustedMobiles(false), publicKeys(false) {}
  bool uid :1;
  bool username :1;
  bool displayName :1;
  bool trustedEmails :1;
  bool trustedMobiles :1;
  bool publicKeys :1;
} _TPlatformProfile__isset;

class TPlatformProfile : public virtual ::apache::thrift::TBase {
 public:

  TPlatformProfile(const TPlatformProfile&);
  TPlatformProfile& operator=(const TPlatformProfile&);
  TPlatformProfile() : uid(0), username(), displayName() {
  }

  virtual ~TPlatformProfile() throw();
  TKey uid;
  std::string username;
  std::string displayName;
  std::map<std::string, bool>  trustedEmails;
  std::map<std::string, bool>  trustedMobiles;
  std::vector<std::string>  publicKeys;

  _TPlatformProfile__isset __isset;

  void __set_uid(const TKey val);

  void __set_username(const std::string& val);

  void __set_displayName(const std::string& val);

  void __set_trustedEmails(const std::map<std::string, bool> & val);

  void __set_trustedMobiles(const std::map<std::string, bool> & val);

  void __set_publicKeys(const std::vector<std::string> & val);

  bool operator == (const TPlatformProfile & rhs) const
  {
    if (!(uid == rhs.uid))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(displayName == rhs.displayName))
      return false;
    if (!(trustedEmails == rhs.trustedEmails))
      return false;
    if (!(trustedMobiles == rhs.trustedMobiles))
      return false;
    if (!(publicKeys == rhs.publicKeys))
      return false;
    return true;
  }
  bool operator != (const TPlatformProfile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TPlatformProfile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TPlatformProfile &a, TPlatformProfile &b);

std::ostream& operator<<(std::ostream& out, const TPlatformProfile& obj);

typedef struct _TDataResult__isset {
  _TDataResult__isset() : errorCode(false), data(false) {}
  bool errorCode :1;
  bool data :1;
} _TDataResult__isset;

class TDataResult : public virtual ::apache::thrift::TBase {
 public:

  TDataResult(const TDataResult&);
  TDataResult& operator=(const TDataResult&);
  TDataResult() : errorCode((TErrorCode::type)0) {
  }

  virtual ~TDataResult() throw();
  TErrorCode::type errorCode;
  TData data;

  _TDataResult__isset __isset;

  void __set_errorCode(const TErrorCode::type val);

  void __set_data(const TData& val);

  bool operator == (const TDataResult & rhs) const
  {
    if (!(errorCode == rhs.errorCode))
      return false;
    if (__isset.data != rhs.__isset.data)
      return false;
    else if (__isset.data && !(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const TDataResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TDataResult &a, TDataResult &b);

std::ostream& operator<<(std::ostream& out, const TDataResult& obj);

}}} // namespace

#endif
