/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TPlatformProfileService_H
#define TPlatformProfileService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "openstarsprofile_types.h"
#include "TDataService.h"

namespace OpenStars { namespace Platform { namespace Profile {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TPlatformProfileServiceIf : virtual public TDataServiceIf {
 public:
  virtual ~TPlatformProfileServiceIf() {}
};

class TPlatformProfileServiceIfFactory : virtual public TDataServiceIfFactory {
 public:
  typedef TPlatformProfileServiceIf Handler;

  virtual ~TPlatformProfileServiceIfFactory() {}

  virtual TPlatformProfileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class TPlatformProfileServiceIfSingletonFactory : virtual public TPlatformProfileServiceIfFactory {
 public:
  TPlatformProfileServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf>& iface) : iface_(iface) {}
  virtual ~TPlatformProfileServiceIfSingletonFactory() {}

  virtual TPlatformProfileServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> iface_;
};

class TPlatformProfileServiceNull : virtual public TPlatformProfileServiceIf , virtual public TDataServiceNull {
 public:
  virtual ~TPlatformProfileServiceNull() {}
};

class TPlatformProfileServiceClient : virtual public TPlatformProfileServiceIf, public TDataServiceClient {
 public:
  TPlatformProfileServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceClient(prot, prot) {}
  TPlatformProfileServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

class TPlatformProfileServiceProcessor : public TDataServiceProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TPlatformProfileServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  TPlatformProfileServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> iface) :
    TDataServiceProcessor(iface),
    iface_(iface) {
  }

  virtual ~TPlatformProfileServiceProcessor() {}
};

class TPlatformProfileServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TPlatformProfileServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TPlatformProfileServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TPlatformProfileServiceIfFactory > handlerFactory_;
};

class TPlatformProfileServiceMultiface : virtual public TPlatformProfileServiceIf, public TDataServiceMultiface {
 public:
  TPlatformProfileServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      TDataServiceMultiface::add(*iter);
    }
  }
  virtual ~TPlatformProfileServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> > ifaces_;
  TPlatformProfileServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TPlatformProfileServiceIf> iface) {
    TDataServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TPlatformProfileServiceConcurrentClient : virtual public TPlatformProfileServiceIf, public TDataServiceConcurrentClient {
 public:
  TPlatformProfileServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceConcurrentClient(prot, prot) {}
  TPlatformProfileServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
